---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: jpbot-api-secrets
  namespace: default
spec:
  encryptedData:
    config.yml: AgAlKprhImEC3ON0N/orjA2pU9GDuqhdEJ53X4O+8KQmWEShJLeub7UFR5r+YL4YrEWSUTrldwzczh0gzeKKgz6XAJNy+/ia7gGQdQZCAfU9tKgnkaLDKm2mKgdNJl0d1xjX/BfEb8mvUyGTAFIeYqJNbaLZJrol73N1uyJ/OWlUze59x3h4UylW/lZdXKcyHlIsyNQ4jU0NFcTSrIjcWfq4mtJI/IVfTSO/TXAGKLwkxobrYzlltispBMfieI0jp3z6b6p7KK54b2iRixGwqKzuuASNe2jZ4YitTIswJqL8V9Q+TcgBp9eHkNvbyxZSQtIbCbF6BAX4QoJH0IAsIuaLYj+ayB8ABzZY3acY0ewsnDFK47sqh+9DGoRVxAwkv/PLsOSpycqs0QV0KGkjIdLiCxiOJ5x4YiffvR7/7oRSiOe39ba2MBK9bpmgMjiU92I9rgtA95fsTLP4eSGsITKFBZfmKqG+yYxNnns+CSOWNTw4gfxoJnia4fgpvisgHY2+zRBUGEyLxoQHExc/Ny3Gp76Ri/LBuMbapEe5MErMAhqy7k50K8lvap0VQ0gkZi+mC6Q1N5V1WpJZzGy2uG+2YehByJrw87PpfYNCenfDIySFzp8JGRWeVmEV4f1E0theDGqguCMFrBy/2zoZfNDkHPrvIIdNuZjHCdbSqN1phru2148jZ80Z1eEnoHBb6tKvvljFBV5qsZ2V5RX+cdhqFjQ/U9tWZ5b23fZpZ900v5yUgkGUs4ZBbfeck1ZmP8PKrlrJzMq0ysEpyA7GezbbtQ5P8Kx0csZXEahZqD5LWiV6DKQ6CeYoR2s5KKBkSPXw8/p6f1EYrHu6TR85EmW4p6VauwPeLxs5rOAv8Rc295sf6NdhCX7ieCz0h1JtYDftr7FsZdrL1a7k+GzSptYzl982FIJzzTUZXGiDF86dwflbBjTIug40A9iDjWB/Od8D7TCLPQZrc4C6AxUPIA95b3lqR5kL0ih6pYZqbICWFlS2BMNkvrF8aJKCJgiJrP0Foc1S0YuMgemZzyVkZvE6kYREZWaaOorXcHVtlHziqoT0sMmpno44K3ZAtO6+vlYWZIUwggnKZLYZcJmBQmdnNVu5GrZuWAEVjAkojMDq5KTPzwQAV8Tn6UPfPMAyf7BjEAVyGe/D
  template:
    metadata:
      creationTimestamp: null
      name: jpbot-api-secrets
      namespace: default
