---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: jpbot-api-secrets
  namespace: default
spec:
  encryptedData:
    config.yml: AgCOzWDR/3YvsHDLuldus6RcEc/55QKZoOiNScnfUDTRMNvHsLRc5109vQ8blWIgS38RQTPVrTgiDBiXJeMx/nLsDw7grmLh2dwcb46lAVuQBqjf8opYhN8eJtI3QKbhYM77gJkEw/VJWY/kOwABdiHIbZtHxWVYIcGU42J/rMRxD7q3Vz/b/b8sUoQAB4uHj54Aeppq1URorkqb4+RKX1P0eiBF1WeyANU28oSqrAF8MZyCxmkRoYdFI7ZxMVefsTZy6E3udy/cYu+1RwQZieggeuQtRuYQEosEG8pPyaARYk4I1e5S6ull5hDogKbDaDs/PHx98TTI3+XWySQFk7Ay6C+ve9U7qkBuVnISFNl72FG7MR5yfmSh5Z7ja64RLbefBKSXZ/ciCfFlLlkLYhMY0LTTS+EfUreYxN06ZFBbhqCGxMlFJmJjAUPLsb3nntOoz3b31+GdyRM4Bn3ZGfxpgpBxPrQIeEKmc/oVj0vcrVGCpY3R/SIJyuxEKT6kqPTaF+yfeOd/OqY+0Cbt/6e38mdl1tM7UBkoM3CyAgb/1FmAzJSkmMhgSy/peYH0byks5qoahD3PWsKpIYVhR/Ti6nU51oYX+h6C8shF+Ycabg7BOQMg7LWHJQ9mKwMIpRkmcqFlPJ2RequsqMhGFTcUJRTxM/fZ8FuuNIpGTeQaOn39hTrAGcv1wqCqzPBd79ibQrsdHoBqgMTIdJuFcLbwFw2Wqgztvhe2i551JiufYHvJJoyo6n+/FdFkbFP655gJk7AfWv/KRdCo/gxOkXH4L5EN2ubL3xAXEOYdJCM5BKqxiPL0YGe7bUT+E4zWCqHU3/zOMQ4DoP0ZjmSvZ4xKWE5+72az1AwF3MDvXJnQ2/SAg9knVXyKz8+RvDa2hJK79xxgp6780f/LnqLDuJeoFuUZUOwQaHH1lLlv5tpqDdEW+VnQV/BiGi6CLPWhXd61MIKmVZc2ypdCncVfPDdA9tAUlMl5jy7mp3Ozo1FKYK8/zeqKPxOz4+jCQyPkPro1wQ/nK0uXWFuq2VDsmmTQoo96e6CVAZ6VdK68JsgGWuj8LSZoayPgZLeV4kjUFR5db17JcEknNByFRwTEVqB2IJt2EAscM+shOJhz8rMdEUWBXYJk4hh8JiJu1bj5yA6m9Shz7muH
  template:
    metadata:
      creationTimestamp: null
      name: jpbot-api-secrets
      namespace: default
